const int    HTTPS_PORT                  = 443;
const long   BAUD_RATE                   = 115200; // Arduino's int is signed by default with a range of -32,768 to 32,767
const char * SSID                        = "Community Keijiban";
const char * STATION_PASSWORD            = "keijiban";
const char * HOME_LANG                   = "en";
const char * FIREBASE_HOST               = "firebasestorage.googleapis.com";
const char * FIREBASE_URL                = "/v0/b/[PROJECT_ID].appspot.com/o/notifiers%2F";
const char * WIFI_NOTICE_BOARD_ID        = "signalId";
const char * WIFI_NOTICE_BOARD_TEXT      = "Signal ID";
const char * WIFI_HOME_ID                = "homeId";
const char * WIFI_HOME_ID_TEXT           = "Home Name";
const char * WIFI_HOME_LANG              = "homeLang";
const char * WIFI_HOME_LANG_TEXT         = "Home Lang (en or jp)";
const char * WIFI_PARAMETER_ATTRIBUTES   = " required";